Repository tjcsl/tin, pull requests merged in 2024-08, with the labels that each got.

#65 Production docs improvement
  docs/source/production.rst
Labels: documentation

#64 Ignore `if TYPE_CHECKING` in coverage report
  pyproject.toml
Labels: testing

#52 Add lots of docstrings
  tin/apps/assignments/models.py
  tin/apps/assignments/views.py
  tin/apps/auth/views.py
  tin/apps/courses/models.py
  tin/apps/courses/views.py
  tin/apps/docs/views.py
  tin/apps/errors/views.py
  tin/apps/submissions/models.py
  tin/apps/submissions/views.py
  tin/apps/users/models.py
  tin/apps/venvs/models.py
  tin/apps/venvs/views.py
  tin/tests/fixtures.py
Labels: documentation

#22 Python 3.11
  .github/workflows/ci.yml
  .github/workflows/deploy-docs.yml
  Pipfile
  Pipfile.lock
  tin/settings/__init__.py
Labels: maintenance

#66 Ruff python
  .gitignore
  pyproject.toml
  tin/apps/assignments/forms.py
  tin/apps/submissions/views.py
  tin/tests/utils.py
Labels: maintenance

#69 Remove tomli dependency in pre-commit
  .pre-commit-config.yaml
  pyproject.toml
Labels: maintenance

#70 Bump dependencies
  Pipfile.lock
Labels: maintenance
