Repository tjcsl/tin, pull requests merged in 2025-06, with the labels that each got.

#86 Fixed submissions not working on dev env
  create_debug_users.py
  docs/source/contributing/setup.rst
  pyproject.toml
  scripts/grader_wrapper.py
  scripts/sample_grader.py
  tin/apps/submissions/tasks.py
  tin/apps/users/management/commands/create_debug_users.py
  tin/apps/users/tests.py
  tin/apps/venvs/tasks.py
  tin/settings/__init__.py
  tin/tests/create_users.py
  tin/tests/fixtures.py
Labels: maintenance

#81 Better test error messages
  Pipfile
  Pipfile.lock
  tin/tests/fixtures.py
Labels: area/testing

#102 Add a filter option to view teacher submissions for an assignment
  tin/apps/assignments/views.py
  tin/templates/assignments/show.html
Labels: app/assignments, area/frontend
